Zemedya.AspNetCoreMVC/Controllers/PanelController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Zemedya.AspNetCoreMVC.Models;
using Zemedya.Business.Abstract.UnitOfWork;
using Zemedya.Entity.Concrete.AcikPozisyonEtities;
using Zemedya.Entity.Concrete.MediaEntities;
using Zemedya.Entity.Concrete.MembershipEntities;
using Zemedya.Entity.Concrete.PressEntities;
using Zemedya.Entity.Concrete.Team;
using Zemedya.Model.DTO.AyarlarDTOs;
using Zemedya.Model.DTO.BlogDTOs;
using Zemedya.Model.DTO.DuyuruDTOs;
using Zemedya.Model.DTO.EkipDTOs;
using Zemedya.Model.DTO.EtkinlikDTOs;
using Zemedya.Model.DTO.GaleriDTOs;
using Zemedya.Model.DTO.GirisDTO;
using Zemedya.Model.DTO.HaberDTOs;
using Zemedya.Model.DTO.IletisimDTOs;
using Zemedya.Model.DTO.KurumsalDTOs;
using Zemedya.Model.DTO.PopupDTOs;
using Zemedya.Model.DTO.ReferansDTOs;
using Zemedya.Model.DTO.SliderDTOs;
using Zemedya.Model.DTO.UrunDTOs;
using Zemedya.Model.DTO.VideoDTOs;
using Zemedya.Model.DTO.YoneticiDTOs;
using Zemedya.Model.VM;
using Zemedya.Model.VM.Page;

namespace Zemedya.AspNetCoreMVC.Controllers
{
    public class PanelController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public PanelController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [Route("/Panel/Career")]
        public IActionResult Video()
        {
            var videolar = _unitOfWork.VideoManager.HepsiniGetir();
            var dil = _unitOfWork.MevcutDillerManager.Getir(x => x.Id == 1);
            ViewBag.en = dil.EN.ToString();
            return View(videolar);
        }

        [Authorize]
        public IActionResult KontrolPaneli()
        {
            KontrolPaneliVM kontrolPaneliVM = new KontrolPaneliVM
            {
                MevcutSayfalar = _unitOfWork.MevcutSayfalarManager.Getir(x => x.Id == 1),
                MevcutDiller = _unitOfWork.MevcutDillerManager.Getir(x => x.Id == 1)
            };
            return View(kontrolPaneliVM);
        }


        public ActionResult PasifeCevirSayfa(string Id)
        {
            var sayfa = _unitOfWork.MevcutSayfalarManager.Getir(x => x.Id == 1);
            if (Id == "1")
            {
                if (sayfa.Haberler)
                {
                    sayfa.Haberler = false;
                }
                else
                {
                    sayfa.Haberler = true;
                }
            }
            else if (Id == "2")
            {
                if (sayfa.Duyuru)
                {
                    sayfa.Duyuru = false;
                }
                else
                {
                    sayfa.Duyuru = true;
                }
            }
            else if (Id == "3")
            {
                if (sayfa.Blog)
                {
                    sayfa.Blog = false;
                }
                else
                {
                    sayfa.Blog = true;
                }
            }
            else if (Id == "31")
            {
                if (sayfa.BlogKategori)
                {
                    sayfa.BlogKategori = false;
                }
                else
                {
                    sayfa.BlogKategori = true;
                }
            }
            else if (Id == "4")
            {
                if (sayfa.Etkinlik)
                {
                    sayfa.Etkinlik = false;
                }
                else
                {
                    sayfa.Etkinlik = true;
                }
            }
            else if (Id == "5")
            {
                if (sayfa.Iletisim)
                {
                    sayfa.Iletisim = false;
                }
                else
                {
                    sayfa.Iletisim = true;
                }
            }
            else if (Id == "6")
            {
                if (sayfa.Kurumsal)
                {
                    sayfa.Kurumsal = false;
                }
                else
                {
                    sayfa.Kurumsal = true;
                }
            }
            else if (Id == "7")
            {
                if (sayfa.Referans)
                {
                    sayfa.Referans = false;
                }
                else
                {
                    sayfa.Referans = true;
                }
            }
            else if (Id == "8")
            {
                if (sayfa.Urunler)
                {
                    sayfa.Urunler = false;
                }
                else
                {
                    sayfa.Urunler = true;
                }
            }
            else if (Id == "81")
            {
                if (sayfa.UrunKategori)
                {
                    sayfa.UrunKategori = false;
                }
                else
                {
                    sayfa.UrunKategori = true;
                }
            }
            else if (Id == "9")
            {
                if (sayfa.Video)
                {
                    sayfa.Video = false;
                }
                else
                {
                    sayfa.Video = true;
                }
            }
            else if (Id == "10")
            {
                if (sayfa.Ekip)
                {
                    sayfa.Ekip = false;
                }
                else
                {
                    sayfa.Ekip = true;
                }
            }
            else if (Id == "11")
            {
                if (sayfa.Galeri)
                {
                    sayfa.Galeri = false;
                }
                else
                {
                    sayfa.Galeri = true;
                }
            }
            else if (Id == "111")
            {
                if (sayfa.GaleriKategori)
                {
                    sayfa.GaleriKategori = false;
                }
                else
                {
                    sayfa.GaleriKategori = true;
                }
            }

            _unitOfWork.MevcutSayfalarManager.Guncelle(sayfa);
            _unitOfWork.Complete();
            _unitOfWork.Dispose();

            return Json(new
            {
                success = true,
            });
        }

        [HttpPost]
        public ActionResult PasifeCevirDil(string Id)
        {
            var dil = _unitOfWork.MevcutDillerManager.Getir(x => x.Id == 1);
            if (Id == "2")
            {
                if (dil.EN)
                {
                    dil.EN = false;
                }
                else
                {
                    dil.EN = true;
                }
            }

            _unitOfWork.MevcutDillerManager.Guncelle(dil);
            _unitOfWork.Complete();
            _unitOfWork.Dispose();

            return Json(new
            {
                success = true,
            });
        }


        [HttpPost]
        public ActionResult VideoEkle([FromForm] VideoDTO videoDTO, IFormFile resim, IFormFile resimEN)
        {
            if (resim != null)
            {
                string uzanti = Path.GetExtension(resim.FileName);
                string resimAd = Guid.NewGuid() + uzanti;
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/" + resimAd);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    resim.CopyTo(stream);
                }
                videoDTO.Gorsel = resimAd;
            }
            else
            {
                videoDTO.Gorsel = "null.png";
            }
            if (resimEN != null)
            {
                string uzantiEN = Path.GetExtension(resimEN.FileName);
                string resimAdEN = Guid.NewGuid() + uzantiEN;
                string pathEN = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/" + resimAdEN);
                using (var streamEN = new FileStream(pathEN, FileMode.Create))
                {
                    resimEN.CopyTo(streamEN);
                }
                videoDTO.GorselEN = resimAdEN;
            }
            else
            {
                videoDTO.GorselEN = "null.png";
            }
            _unitOfWork.VideoManager.Ekle(videoDTO);
            _unitOfWork.Complete();
            _unitOfWork.Dispose();
            return Json(new
            {
                success = true,
                result = 1
            });
        }


        public ActionResult VideoGuncelle([FromForm] string Id)
        {
            var entity = _unitOfWork.VideoManager.Getir(x => x.Id == int.Parse(Id));
            return Json(new
            {
                success = true,
                ad = entity.Ad,
                adEN = entity.AdEN,
                baslik = entity.Baslik,
                baslikEN = entity.BaslikEN,
                videourl = entity.VideoUrl,
                videourlEN = entity.VideoUrlEN,
                gorsel = entity.Gorsel,
                gorselEN = entity.GorselEN,
                aktif = entity.Aktif
            });
        }

        public ActionResult VideoGuncel([FromForm] VideoDTO videoDTO, IFormFile resim, IFormFile resimEN)
        {
            var video = _unitOfWork.VideoManager.Getir(x => x.Id == videoDTO.Id);
            if (resim != null)
            {
                string uzanti = Path.GetExtension(resim.FileName);
                string resimAd = Guid.NewGuid() + uzanti;
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/" + resimAd);

Zemedya.AspNetCoreMVC/Views/Panel/Certificates.cshtml
@model List<Zemedya.Entity.Concrete.MembershipEntities.Membership>

@{
    ViewData["Title"] = "Certificates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container ">
    <div class="card card-custom">
        <div class="card-header flex-wrap-border-0 pt-6 pb-0">

            <div class="card-title">
                <h3 class="card-label font-size-h3-lg mb-7">
                    <i class="flaticon2-gear text-primary"></i>
                    Certificates
                </h3>
            </div>

            <div>
                <a href="/Panel/CertificatesAddOrUpdate" class="btn btn-primary font-weight-bolder">
                    <i class="fas fa-plus"></i>	Yeni Sertifika Ekle
                </a>
            </div>
        </div>
        <div class="card-body">
            @if (Model.Count > 0)
            {
                @foreach (var membership in Model.OrderBy(x => x.Order))
                {
                    <div class="card card-custom shadow mb-5">
                        <div class="card-header">
                            <div class="card-title">
                                <h3 class="card-label">
                                    @membership.Title
                                </h3>
                            </div>
                            <div class="card-toolbar">
                                <a href="/Panel/CertificatesUp?id=@membership.Id" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                    <i class="flaticon2-up"></i>
                                </a>
                                <a href="/Panel/CertificatesDown?id=@membership.Id" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                    <i class="flaticon2-down"></i>
                                </a>
                                <a href="/Panel/CertificatesAddOrUpdate?id=@membership.Id" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                    <i class="flaticon-edit-1"></i>
                                </a>
                                <button onclick="DeleteMessage('/Panel/CertificatesDelete?id=@membership.Id')" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                    <i class="flaticon-delete-1"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="alert alert-secondary text-center" role="alert">
                    Kayıt yok.
                </div>
            }
        </div>
    </div>
</div>


@section Javascript{
    <script>
        function DeleteMessage(url) {
            Swal.fire({
                title: 'Silmek istiyor musunuz?',
                text: "Bu işlemi geri alamazsınız!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Kapat',
                confirmButtonText: 'Evet, sil!'
            }).then((result) => {
                if (result.isConfirmed) {

                    window.location = url;
                }
            })
        }
    </script>

}

Zemedya.AspNetCoreMVC/Views/Panel/ImageMediaItems.cshtml
@model Zemedya.Entity.Concrete.MediaEntities.ImageMediaCategory
@{
    ViewData["Title"] = "ImageMediaItems";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container ">
    <div class="card card-custom">
        <div class="card-header flex-wrap-border-0 pt-6 pb-0">

            <div class="card-title">
                <h3 class="card-label font-size-h3-lg mb-7">
                    <i class="flaticon2-gear text-primary"></i>
                    @Model.NameTR
                </h3>
            </div>

            <div>
                <a href="/Panel/ImageMediaItemAddOrUpdate?imageMediaCategoryId=@Model.Id" class="btn btn-primary font-weight-bolder">
                    <i class="fas fa-plus"></i>	Yeni Öğe Ekle
                </a>
            </div>
        </div>
        <div class="card-body">
            @if (Model.ImageMediaItems.Count > 0)
            {
                <div class="row">

                    @foreach (var item in Model.ImageMediaItems)
                    {
                        <div class="col-lg-2">
                            <div class="card">
                                <img class="card-img-top" src="/img/@item.Image">
                                <div class="card-body p-3">
                                    <p class="card-text text-center m-0">@item.DescriptionTR</p>
                                </div>
                                <div class="card-footer p-3 d-flex justify-content-between">
                                    <a href="/Panel/ImageMediaItemAddOrUpdate?id=@item.Id" class="btn btn-sm btn-icon"><i class="flaticon-edit-1"></i></a>
                                    <button onclick="DeleteMessage('/Panel/ImageMediaItemDelete?id=@item.Id&imageMediaCategoryId=@Model.Id')" class="btn btn-sm btn-icon"><i class="flaticon-delete-1"></i></button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
            else
            {
                <div class="alert alert-secondary text-center" role="alert">
                    Öğe yok.
                </div>
            }
        </div>
    </div>
</div>


@section Javascript{
    <script>
        function DeleteMessage(url) {
            Swal.fire({
                title: 'Silmek istiyor musunuz?',
                text: "Bu işlemi geri alamazsınız!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Kapat',
                confirmButtonText: 'Evet, sil!'
            }).then((result) => {
                if (result.isConfirmed) {

                    window.location = url;
                }
            })
        }
    </script>
}

Zemedya.AspNetCoreMVC/Views/Panel/Membership.cshtml
@model List<Zemedya.Entity.Concrete.MembershipEntities.Membership>
@{
    ViewData["Title"] = "Membership";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container ">
    <div class="card card-custom">
        <div class="card-header flex-wrap-border-0 pt-6 pb-0">

            <div class="card-title">
                <h3 class="card-label font-size-h3-lg mb-7">
                    <i class="flaticon2-gear text-primary"></i>
                    Membership
                </h3>
            </div>

            <div>
                <a href="/Panel/MembershipAddOrUpdate" class="btn btn-primary font-weight-bolder">
                    <i class="fas fa-plus"></i>	Yeni Üyelik Ekle
                </a>
            </div>
        </div>
        <div class="card-body">
            @if (Model.Count > 0)
                {
                    @foreach (var membership in Model.OrderBy(x => x.Order))
                    {
                        <div class="card card-custom shadow mb-5">
                            <div class="card-header">
                                <div class="card-title">
                                    <h3 class="card-label">
                                        @membership.Title
                                    </h3>
                                </div>
                                <div class="card-toolbar">
                                    <a href="/Panel/membershipUp?id=@membership.Id" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                        <i class="flaticon2-up"></i>
                                    </a>
                                    <a href="/Panel/membershipDown?id=@membership.Id" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                        <i class="flaticon2-down"></i>
                                    </a>
                                    <a href="/Panel/MembershipAddOrUpdate?id=@membership.Id" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                        <i class="flaticon-edit-1"></i>
                                    </a>
                                    <button onclick="DeleteMessage('/Panel/membershipDelete?id=@membership.Id')" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                        <i class="flaticon-delete-1"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="alert alert-secondary text-center" role="alert">
                        Kayıt yok.
                    </div>
                }
        </div>
    </div>
</div>


@section Javascript{
    <script>
        function DeleteMessage(url) {
            Swal.fire({
                title: 'Silmek istiyor musunuz?',
                text: "Bu işlemi geri alamazsınız!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Kapat',
                confirmButtonText: 'Evet, sil!'
            }).then((result) => {
                if (result.isConfirmed) {

                    window.location = url;
                }
            })
        }
    </script>

}

Zemedya.AspNetCoreMVC/Views/Panel/OdaGuncelle.cshtml
@{
    ViewData["Title"] = "OdaGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>OdaGuncelle</h1>

Zemedya.AspNetCoreMVC/Views/Panel/Odalar.cshtml
@model IEnumerable<Zemedya.Entity.Concrete.OdaEntities.Oda>
@{
    ViewData["Title"] = "Odalar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container ">
    <div class="card card-custom">
        <div class="card-header flex-wrap-border-0 pt-6 pb-0">

            <div class="card-title">
                <h3 class="card-label font-size-h3-lg mb-7">
                    <i class="flaticon2-gear text-primary"></i>
                    Oda Listesi
                </h3>
            </div>

            <div>
                <a asp-action="UrunEkle" asp-controller="Panel" class="btn btn-primary font-weight-bolder">
                    <i class="fas fa-plus"></i>	Yeni Ekle
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="example-preview">
                <table class="table table-striped table-hover table-bordered " id="dataTable" style="width:100%">
                    <thead>
                        <tr>
                            <th scope="col">Sıralama No</th>
                            <th scope="col">İsim</th>
                            @*@if (ViewBag.kategori == "True")
                            {
                                <th scope="col">Kategori</th>
                            }*@
                            <th scope="col" style="width:50px;">Aktif</th>
                            <th scope="col" style="width:50px;">Güncelle</th>
                            <th scope="col" style="width:50px;">Sil</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.SıraNo</td>
                                <td>@item.Isim</td>
                                @*@if (ViewBag.kategori == "True")
                                {
                                    <td>@item.UrunKategori.Isim</td>
                                }*@

                                <td>
                                    @if (item.Aktif)
                                    {
                                        <a data-id="@item.Id" class="aktif btn btn-sm font-weight-bold btn-light-primary btn-inline ml-2">Aktif</a>
                                    }
                                    else
                                    {
                                        <a data-id="@item.Id" class="aktif btn btn-sm font-weight-bold btn-light-danger btn-inline ml-2">Pasif</a>
                                    }

                                </td>
                                <td>
                                    <a href="/Panel/OdaGuncelle/@item.Id"><i class="flaticon-refresh text-warning icon-xl ml-8"></i></a>
                                </td>
                                <td>
                                    <a data-id="@item.Id" class="Sil btn flaticon-delete text-danger icon-xl ml-2"></a>
                                </td>

                            </tr>

                        }



                    </tbody>
                </table>
            </div>
        </div>
    </div>



</div>

@section Javascript{
    <script type="text/javascript">

        $(document).ready(function () {
            $(".Sil").on("click", function () {
                var Id = $(this).attr("data-id");
                var data = new FormData();
                data.append("Id", Id);
                Swal.fire({
                title: "Oda silinecek, Emin misiniz?",
                showCancelButton: true,
                confirmButtonText: "Evet",
                cancelButtonText: "İptal",
            }).then(function (result) {
                if (result.value) {

                    $.ajax({
                    url: '@Url.Action("OdaSil", "Panel")',
                    type: "POST",
                    processData: false,
                    contentType: false,
                    data: data,
                    success: function (data) {
                        swal.fire({
                            text: "Oda Başarıyla Silindi.",
                            icon: "success",
                            buttonsStyling: true,
                            confirmButtonText: "Tamam",
                            customClass: {
                                confirmButton: "btn font-weight-bold btn-light-primary"
                            }
                        }).then((result) => {
                            if (result.isConfirmed) {
                                window.location.reload();
                            }
                        })
                    }
                });
                }
            });
            });
        });

        $(document).ready(function () {
            $('#dataTable').DataTable();
        });

        $(document).ready(function () {
            $(".aktif").on("click", function () {
                var Id = $(this).attr("data-id");
                var data = new FormData();
                data.append("Id", Id);
                $.ajax({
                    url: '@Url.Action("PasifeCevirOda", "Panel")',
                    type: "POST",
                    processData: false,
                    contentType: false,
                    data: data,
                    success: function (data) {
                        window.location.reload();
                    }
                });
            });
        });


    </script>
}

Zemedya.AspNetCoreMVC/Views/Panel/OpenPositionAddOrUpdate.cshtml
@model Zemedya.Entity.Concrete.AcikPozisyonEtities.AcikPozisyon
@{
    ViewData["Title"] = "Open Position Add Or Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form method="POST" enctype="multipart/form-data" class="container" id="Form">
    <div class="card card-custom">
        <div class="card-header flex-wrap-border-0 pt-6 pb-0">

            <div class="card-title">
                <h3 class="card-label font-size-h3-lg mb-7">
                    <i class="flaticon2-gear text-primary"></i>
                    Açık Posizyon Düzenleme
                </h3>
            </div>

            <div>
                <button type="submit" class="btn btn-primary font-weight-bolder">
                    Kaydet
                </button>
            </div>
        </div>
        <div class="card-body">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label>Adı (TR)</label>
                <input class="form-control" type="text" maxlength="300" required="required" asp-for="NameTr" />
            </div>
            <div class="form-group">
                <label>Adı (EN)</label>
                <input class="form-control" type="text" maxlength="300" required="required" asp-for="NameEn" />
            </div>
            <div class="form-group">
                <label>Şehir</label>
                <input class="form-control" type="text" maxlength="100" required="required" asp-for="City" />
            </div>
            <div class="form-group">
                <label>Açıklama (TR)</label>
                <textarea class="form-control" asp-for="DescriptionTr"></textarea>
            </div>
            <div class="form-group">
                <label>Açıklama (EN)</label>
                <textarea class="form-control" asp-for="DescriptionEn"></textarea>
            </div>
        </div>
    </div>
</form>

@section Javascript{
    <script>
        $('#DescriptionTr').summernote();
        $('#DescriptionEn').summernote();

        $("#Form").validate({
            lang: 'tr',
            submitHandler: function (form) {
                form.submit();
            }
        });

    </script>
}

Zemedya.AspNetCoreMVC/Views/Panel/Press.cshtml
@model List<Zemedya.Entity.Concrete.PressEntities.Press>
@{
    ViewData["Title"] = "Press";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container ">
    <div class="card card-custom">
        <div class="card-header flex-wrap-border-0 pt-6 pb-0">

            <div class="card-title">
                <h3 class="card-label font-size-h3-lg mb-7">
                    <i class="flaticon2-gear text-primary"></i>
                    Press
                </h3>
            </div>

            <div>
                <a href="/Panel/PressAddOrUpdate" class="btn btn-primary font-weight-bolder">
                    <i class="fas fa-plus"></i>	Yeni Yayın Ekle
                </a>
            </div>
        </div>
        <div class="card-body">
            @if (Model.Count > 0)
            {
                @foreach (var press in Model.OrderBy(x => x.Order))
                {
                    <div class="card card-custom shadow mb-5">
                        <div class="card-header">
                            <div class="card-title">
                                <h3 class="card-label">
                                    @press.BaslikTR
                                </h3>
                            </div>
                            <div class="card-toolbar">
                                <a href="/Panel/PressUp?id=@press.Id" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                    <i class="flaticon2-up"></i>
                                </a>
                                <a href="/Panel/PressDown?id=@press.Id" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                    <i class="flaticon2-down"></i>
                                </a>
                                <a href="/Panel/PressAddOrUpdate?id=@press.Id" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                    <i class="flaticon-edit-1"></i>
                                </a>
                                <button onclick="DeleteMessage('/Panel/PressDelete?id=@press.Id')" class="btn btn-sm btn-secondary font-weight-bold mr-2">
                                    <i class="flaticon-delete-1"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="alert alert-secondary text-center" role="alert">
                    Kayıt yok.
                </div>
            }
        </div>
    </div>
</div>


@section Javascript{
    <script>
        function DeleteMessage(url) {
            Swal.fire({
                title: 'Silmek istiyor musunuz?',
                text: "Bu işlemi geri alamazsınız!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Kapat',
                confirmButtonText: 'Evet, sil!'
            }).then((result) => {
                if (result.isConfirmed) {

                    window.location = url;
                }
            })
        }
    </script>

}