Zemedya.AspNetCoreMVC/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Zemedya.Business.Abstract.UnitOfWork;
using Zemedya.Entity.Concrete.BlogEntities;
using Zemedya.Entity.Concrete.GaleriEntities;
using Zemedya.Entity.Concrete.VideoEntities;
using Zemedya.Model.DTO.BlogDTOs;
using Zemedya.Model.DTO.DuyuruDTOs;
using Zemedya.Model.DTO.EkipDTOs;
using Zemedya.Model.DTO.EmailDTOs;
using Zemedya.Model.DTO.VideoDTOs;
using Zemedya.Model.VM.Page;

namespace Zemedya.AspNetCoreMVC.Controllers
{
    public class PageController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public PageController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        [Route("/tr")]
        public IActionResult Media()
        {
            var siteBilgisi = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            if (siteBilgisi.GoogleDogrulamaKodu != null)
            {
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Trim();
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Replace('"', ' ');
                int koduzunluk = siteBilgisi.GoogleDogrulamaKodu.Length - 6;
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Substring(5, koduzunluk);
            }

            if (siteBilgisi.SiteTitle == null)
            {
                siteBilgisi.SiteTitle = "Zemedya";
            }
            if (siteBilgisi.GoogleAnalyticsKodu == null)
            {
                siteBilgisi.GoogleAnalyticsKodu = "google";
            }
            AnasayfaVM anasayfaVM = new AnasayfaVM()
            {
                Sliderlar = _unitOfWork.SliderManager.HepsiniGetir(x => x.Aktif),
                Title = siteBilgisi.SiteTitle.Trim(),
                GoogleDogrulama = siteBilgisi.GoogleDogrulamaKodu,
                Favicon = siteBilgisi.Favicon,
                GoogleAnalytics = siteBilgisi.GoogleAnalyticsKodu.Trim(),
                BlogKategoriListesi = _unitOfWork.BlogKategoriManager.HepsiniGetir(x => x.Aktif),
                Solutions = _unitOfWork.DuyuruManager.HepsiniGetir(x => x.Aktif == true),
                Referans = _unitOfWork.ReferansManager.HepsiniGetir(x => x.Aktif == true),
                KurumsalDTO = _unitOfWork.KurumsalManager.Getir(x => x.Id == 1)
            };
            if (siteBilgisi.Description != null)
            {
                ViewBag.description = siteBilgisi.Description.Trim();
            }
            return View(anasayfaVM);
        }

        [Route("")]
        public IActionResult MediaEN()
        {
            var siteBilgisi = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            if (siteBilgisi.GoogleDogrulamaKodu != null)
            {
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Trim();
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Replace('"', ' ');
                int koduzunluk = siteBilgisi.GoogleDogrulamaKodu.Length - 6;
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Substring(5, koduzunluk);
            }

            if (siteBilgisi.SiteTitleEN == null)
            {
                siteBilgisi.SiteTitleEN = "Zemedya";
            }
            if (siteBilgisi.GoogleAnalyticsKodu == null)
            {
                siteBilgisi.GoogleAnalyticsKodu = "google";
            }
            AnasayfaVM anasayfaVM = new AnasayfaVM()
            {
                Sliderlar = _unitOfWork.SliderManager.HepsiniGetir(x => x.Aktif),
                Title = siteBilgisi.SiteTitleEN.Trim(),
                GoogleDogrulama = siteBilgisi.GoogleDogrulamaKodu,
                Favicon = siteBilgisi.Favicon,
                GoogleAnalytics = siteBilgisi.GoogleAnalyticsKodu.Trim(),
                BlogKategoriListesi = _unitOfWork.BlogKategoriManager.HepsiniGetir(x => x.Aktif),
                Solutions = _unitOfWork.DuyuruManager.HepsiniGetir(x => x.Aktif == true),
                Referans = _unitOfWork.ReferansManager.HepsiniGetir(x => x.Aktif == true),
                KurumsalDTO = _unitOfWork.KurumsalManager.Getir(x => x.Id == 1)
            };
            if (siteBilgisi.DescriptionEN != null)
            {
                ViewBag.description = siteBilgisi.DescriptionEN.Trim();
            }
            return View(anasayfaVM);
        }




        [Route("iletisim")]
        public IActionResult Iletisim()
        {
            var siteBilgisi = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            if (siteBilgisi.GoogleDogrulamaKodu != null)
            {
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Trim();
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Replace('"', ' ');
                int koduzunluk = siteBilgisi.GoogleDogrulamaKodu.Length - 6;
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Substring(5, koduzunluk);
            }
            var iletisim = _unitOfWork.IletisimManager.Getir(x => x.Id == 1);
            ViewBag.facebook = siteBilgisi.Facebook;
            ViewBag.twitter = siteBilgisi.Twitter;
            ViewBag.linkedin = siteBilgisi.Linkedin;
            ViewBag.googledogrulama = siteBilgisi.GoogleDogrulamaKodu;
            if (siteBilgisi.Description != null)
            {
                ViewBag.description = siteBilgisi.Description.Trim();
            }
            if (siteBilgisi.GoogleAnalyticsKodu != null)
            {
                ViewBag.googleanalytics = siteBilgisi.GoogleAnalyticsKodu.Trim();
            }
            ViewBag.favicon = siteBilgisi.Favicon;
            return View(iletisim);
        }


        [Route("contact/{seo}")]
        public IActionResult Contact(string seo)
        {
            var siteBilgisi = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            if (siteBilgisi.GoogleDogrulamaKodu != null)
            {
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Trim();
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Replace('"', ' ');
                int koduzunluk = siteBilgisi.GoogleDogrulamaKodu.Length - 6;
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Substring(5, koduzunluk);
            }
            var iletisim = _unitOfWork.IletisimManager.Getir(x => x.Id == 1);
            ViewBag.googledogrulama = siteBilgisi.GoogleDogrulamaKodu;
            if (siteBilgisi.DescriptionEN != null)
            {
                ViewBag.descriptionEN = siteBilgisi.DescriptionEN.Trim();
            }
            if (siteBilgisi.Description != null)
            {
                ViewBag.description = siteBilgisi.Description.Trim();
            }
            if (siteBilgisi.GoogleAnalyticsKodu != null)
            {
                ViewBag.googleanalytics = siteBilgisi.GoogleAnalyticsKodu.Trim();
            }
            ViewBag.favicon = siteBilgisi.Favicon;
            if (seo == "en")
            {
                ViewBag.en = "true";
            }
            return View(iletisim);
        }



        public ActionResult EmailGonder([FromForm] EmailDTO emailDTO, IFormFile dosya)
        {
            try
            {
                var ayarlar = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
                SmtpClient client = new SmtpClient(ayarlar.Server, int.Parse(ayarlar.Port));
                client.Credentials = new NetworkCredential(ayarlar.Adres, ayarlar.Sifre);
                client.EnableSsl = false;
                MailMessage msj = new MailMessage();

                msj.From = new MailAddress("website@platinum-ms.com", emailDTO.Ad + " " + emailDTO.Soyad);



                msj.Body = "Ad Soyad:  " + emailDTO.Ad + " " + emailDTO.Soyad + Environment.NewLine + "Telefon:   " + emailDTO.Telefon + Environment.NewLine + "Email:     " + emailDTO.EpostaAdı + Environment.NewLine + "Konu:      " + emailDTO.Konu + Environment.NewLine + "Mesaj:     " + emailDTO.Mesaj;
                if (dosya != null)
                {
                    string FileName = Path.GetFileName(dosya.FileName);
                    msj.Attachments.Add(new Attachment(dosya.OpenReadStream(), FileName));
                    msj.To.Add(ayarlar.IletilecekAdres2);
                    if (ayarlar.WhatsappMesaj != null)
                    {
                        msj.Subject = ayarlar.WhatsappMesaj;
                    }
                    else
                    {
                        msj.Subject = emailDTO.Konu;
                    }

                }
                else
                {
                    if (ayarlar.WhatsappTelefon != null)
                    {
                        msj.Subject = ayarlar.WhatsappTelefon;
                    }
                    else
                    {
                        msj.Subject = emailDTO.Konu;
                    }
                    msj.To.Add(ayarlar.IletilecekAdres);
                }
                client.Send(msj);
                return Json(new
                {
                    success = true,
                    result = 1
                });

            }
            catch (Exception)
            {

                return Json(new
                {
                    success = true,
                    result = 2
                });
            }

        }





        public ActionResult SiteBilgileri(string bilgi)
        {
            var ayarlar = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            return Json(new
            {
                success = true,
                whatsapptel = ayarlar.WhatsappTelefon,
                whatsappdurum = ayarlar.WhatsappDurum,
                whatsappMesaj = ayarlar.WhatsappMesaj,

Zemedya.AspNetCoreMVC/Views/Page/Corporate.cshtml
@model Zemedya.Model.DTO.BlogDTOs.BlogKategoriDTO
@{
    if (ViewBag.en == "true")
    {
        ViewData["Title"] = Model.IsimEN;
        ViewData["description"] = ViewBag.descriptionEN;
    }
    else
    {
        ViewData["Title"] = Model.Isim;
        ViewData["description"] = ViewBag.description;

    }
    ViewData["googledogrulama"] = ViewBag.googleDogrulama;
    ViewData["favicon"] = ViewBag.favicon;
    ViewData["googleanalytics"] = ViewBag.googleanalytics;
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

@if (ViewBag.en == "true")
{
    <section class="hero pb-5">
        <span class="image image-overlay" style="background-image: url(/img/@Model.GorselEN)"></span>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 text-white">
                    <span class="eyebrow decorated mb-1">Corporate</span>
                    <h1 class="mb-2 text-shadow">@Model.IsimEN</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Corporate</a></li>
                            <li class="breadcrumb-item active">@Model.IsimEN</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    @Html.Raw(Model.DetayEN)
                </div>
            </div>
        </div>
    </section>
}
else
{
    <section class="hero pb-5">
        <span class="image image-overlay" style="background-image: url(/img/@Model.Gorsel)"></span>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 text-white">
                    <span class="eyebrow decorated mb-1">Kurumsal</span>
                    <h1 class="mb-2 text-shadow">@Model.Isim</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/tr">Ana Sayfa</a></li>
                            <li class="breadcrumb-item"><a href="#">Kurumsal</a></li>
                            <li class="breadcrumb-item active">@Model.Isim</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    @Html.Raw(Model.Detay)
                </div>
            </div>
        </div>
    </section>
}

Zemedya.AspNetCoreMVC/Views/Page/Iletisim.cshtml
@model Zemedya.Model.DTO.IletisimDTOs.IletisimDTO
@{
    ViewData["Title"] = "İletişim";
    ViewData["description"] = ViewBag.description;
    ViewData["googledogrulama"] = ViewBag.googleDogrulama;
    ViewData["favicon"] = ViewBag.favicon;
    ViewData["googleanalytics"] = ViewBag.googleanalytics;
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<div class="alt-sayfa-baslik">
    <div class="container">
        <div class="ust-kategori-baslik">İletişim</div>
        <h1>Bize Ulaşın</h1>
    </div>
</div>

<section class="section section-lg bg-default">
    <div class="container">
        <div class="layout-bordered">
            <div class="layout-bordered__aside">
                <div class="layout-bordered__aside-item">
                    <p class="heading-8">Adres</p>
                    <div class="unit flex-row unit-spacing-xxs">
                        <div class="unit__left"><span class="icon icon-sm icon-primary material-icons-location_on"></span></div>
                        <div class="unit__body">@Model.Adres</div>
                    </div>
                </div>

                <div class="layout-bordered__aside-item">
                    <p class="heading-8">Telefon</p>
                    <div class="unit flex-row unit-spacing-xxs">
                        <div class="unit__left"><span class="icon icon-sm icon-primary material-icons-local_phone"></span></div>
                        <div class="unit__body"><a href="tel:#">@Model.Telefon</a></div>
                        <div class="unit__body"><a href="tel:#">@Model.Telefon</a></div>
                    </div>
                </div>
                @if (Model.Fax != null)
                {
                    <div class="layout-bordered__aside-item">
                        <p class="heading-8">Faks</p>
                        <div class="unit flex-row unit-spacing-xxs">
                            <div class="unit__left"><span class="icon icon-sm icon-primary mdi mdi-fax"></span></div>
                            <div class="unit__body"><a href="tel:#">@Model.Fax</a></div>
                        </div>
                    </div>
                }

                <div class="layout-bordered__aside-item">
                    <p class="heading-8">Sosyal Medya</p>
                    <ul class="list-inline-xs">
                        @if (ViewBag.facebook != null)
                        {
                            <li><a class="icon icon-sm icon-default fa fa-facebook" target="_blank" href="@ViewBag.facebook"></a></li>
                        }
                        @if (ViewBag.twitter != null)
                        {
                            <li><a class="icon icon-sm icon-default fa fa-twitter" target="_blank" href="@ViewBag.twitter"></a></li>
                        }
                        @if (ViewBag.linkedin != null)
                        {
                            <li><a class="icon icon-sm icon-default fa fa-linkedin" target="_blank" href="@ViewBag.linkedin"></a></li>
                        }

                    </ul>
                </div>

            </div>
            <div class="layout-bordered__main text-center">
                <div class="layout-bordered__main-inner">
                    <h3>İletişim formu</h3>
                    <p>Bize ulaşmak için alttaki formu doldurun.</p>
                    <!-- RD Mailform-->
                    <form class="rd-mailform" id="Emailform" method="post">
                        <div class="row align-items-md-end row-20">
                            <div class="col-md-6">
                                <div class="form-wrap">
                                    <input class="form-input form-control-has-validation" placeholder="Ad/Soyad" id="name" type="text"
                                           name="name">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-wrap">
                                    <input class="form-input form-control-has-validation" id="phone" placeholder="Telefon" type="text" name="phone"
                                           >
                                    
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-wrap">
                                    
                                    <textarea class="form-input form-control-has-validation form-control-last-child" id="message"
                                              name="message" placeholder="Mesajınız"></textarea>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-wrap">
                                    <input class="form-input form-control-has-validation" id="email" type="email" name="email"
                                  placeholder="Email">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <button class="button button-block button-primary" onclick="return epostaGonder()">Mesaj Gönder</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</section>
<section class="kroki">
    <iframe src="@Model.HaritaKod" width="100%" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</section>

@*<section class="contact_info_area sec_pad bg_color">
    <div class="container">


        <div class="contact_form">
            <h2 class="f_p f_size_22 t_color3 f_600 l_height28 mt_100 mb_40">Leave a Message</h2>
            <form class="contact_form_box" method="post" id="Emailform">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group text_box">
                            <input type="text" id="name" name="name" placeholder="Ad ve Soyad">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group text_box">
                            <input type="text" name="email" id="email" placeholder="E-Posta Adresiniz">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group text_box">
                            <input type="text" id="subject" name="subject" placeholder="Konu">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-group text_box">
                            <textarea name="message" id="message" cols="30" rows="10" placeholder="Mesajınızı buraya giriniz..."></textarea>
                        </div>
                    </div>
                </div>
                <button type="submit" onclick="return epostaGonder()" class="btn_three">Mesaj Gönder</button>
            </form>
        </div>
    </div>
</section>*@


@section Javascript{
    <script type="text/javascript">
        $(document).ready(function () {
            habervalidator = $("#Emailform").validate({
                rules: {
                    name: {
                        required: true,
                    },
                    email: {
                        required: true,
                        email: true,
                    },
                    phone: {
                        required: true,
                    },
                    subject: {
                        required: true,
                    },
                    message: {
                        required: true,
                    }
                },
                messages: {
                    name: {
                        required: "Bu alan boş geçilemez."
                    },
                    phone: {
                        required: "Bu alan boş geçilemez."
                    },
                    email: {
                        required: "Bu alan boş geçilemez.",
                        email : "Lütfen geçerli bir e-posta adresi giriniz."
                    },
                    subject: {
                        required: "Bu alan boş geçilemez."
                    },
                    message: {
                        required: "Bu alan boş geçilemez."
                    }
                }
            });
        });

        function EpostaGonder() {
            var form = new FormData();
            form.append("EpostaAdı", $('#email').val());
            form.append("AdSoyad", $('#name').val());
            form.append("Konu", $('#subject').val());
            form.append("Mesaj", $('#message').val());
            form.append("Telefon", $('#phone').val());

            $.ajax({
                url: '@Url.Action("EmailGonder", "Page")',
                type: "POST",
                processData: false,
                contentType: false,
                data: form,
                success: function (data) {
                    if (data.result == 1) {
                        swal.fire({
                            text: "Mesajınız başarıyla gönderildi.",
                            icon: "success",
                            buttonsStyling: true,
                            confirmButtonText: "Tamam",
                            customClass: {
                                confirmButton: "btn font-weight-bold btn-light-primary"
                            }
                        })
                    }
                    else {
                        swal.fire({
                            text: "Mesaj Gönderilemedi.",
                            icon: "error",
                            buttonsStyling: true,
                            confirmButtonText: "Tamam",
                            customClass: {
                                confirmButton: "btn font-weight-bold btn-light-primary"
                            }
                        })
                    }
                }
            });
        }

        var habervalidator;

        function epostaGonder() {
            if (habervalidator.form()) {
                EpostaGonder();
                return false;
            }
            else {
                swal.fire({
                    text: "Lütfen bilgileri eksiksiz giriniz.",
                    icon: "error",
                    buttonsStyling: true,
                    confirmButtonText: "Tamam",
                    customClass: {
                        confirmButton: "btn font-weight-bold btn-light-primary"
                    }
                })


                return false;
            }
        }
    </script>
}

Zemedya.AspNetCoreMVC/Views/Page/OpenPosition.cshtml
@model Zemedya.Entity.Concrete.AcikPozisyonEtities.AcikPozisyon

@{
    if (ViewBag.en == "true")
    {
        ViewData["Title"] = Model.NameEn;
    }
    else
    {
        ViewData["Title"] = Model.NameTr;

    }

    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<section class="hero pb-5">
    <span class="image image-overlay" style="background-image: url(/img/d1b836aa-a805-4b25-a18c-048a1517454e.jpg)"></span>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-8 text-white">
                @if (ViewBag.Lang == "en")
                {
                    <h1 class="mb-2 text-shadow">Open Position</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Carrer</a></li>
                            <li class="breadcrumb-item"><a href="#">Human Resources</a></li>
                            <li class="breadcrumb-item active">@Model.NameEn</li>
                        </ol>
                    </nav>
                }
                else
                {
                    <h1 class="mb-2 text-shadow">Açık Pozisyonlar</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
                            <li class="breadcrumb-item"><a href="#">Kariyer</a></li>
                            <li class="breadcrumb-item"><a href="#">İnsan Kaynakları</a></li>
                            <li class="breadcrumb-item active">@Model.NameTr</li>
                        </ol>
                    </nav>
                }
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col">
                @if (ViewBag.Lang == "en")
                {
                    <div class="border-bottom border-bottom-dark d-flex justify-content-between mb-2">
                        <h3>@Model.NameEn</h3>
                        <h4>@Model.City</h4>
                    </div>
                    <div class="mb-2">
                        @Html.Raw(Model.DescriptionEn)
                    </div>
                    <div class="d-flex justify-content-center mb-2">
                        <button onclick="CarrerModal('@Model.NameEn (@Model.City) Aplly')" class="btn btn-secondary">Apply</button>
                    </div>
                }
                else
                {
                    <div class="border-bottom border-bottom-dark d-flex justify-content-between mb-2">
                        <h3>@Model.NameTr</h3>
                        <h4>@Model.City</h4>
                    </div>
                    <div class="mb-2">
                        @Html.Raw(Model.DescriptionTr)
                    </div>
                    <div class="d-flex justify-content-center mb-2">
                        <button onclick="CarrerModal('@Model.NameEn (@Model.City) Başvuru')" class="btn btn-secondary">Başvur</button>
                    </div>

                }
            </div>
        </div>
    </div>

</section>




@section Javascript{
    <script type="text/javascript">
        $(document).ready(function () {
            habervalidator = $("#Emailform").validate({
                rules: {
                    name: {
                        required: true,
                    },
                    surname: {
                        required: true,
                    },
                    email: {
                        required: true,
                        email: true,
                    },
                    phone: {
                        required: true,
                    },
                    subject: {
                        required: true,
                    },
                    message: {
                        required: true,
                    }
                },
                messages: {
                    name: {
                        required: "This field is required."
                    },
                    surname: {
                        required: "This field is required."
                    },
                    phone: {
                        required: "This field is required."
                    },
                    email: {
                        required: "This field is required.",
                        email: "Please enter a valid e-mail address."
                    },
                    subject: {
                        required: "This field is required."
                    },
                    message: {
                        required: "This field is required."
                    }
                }
            });
        });

        function CarrerModal(konu) {

        }

        function EpostaGonder() {
            var file = $("#file").get(0).files;
            var form = new FormData();
            form.append("EpostaAdı", $('#email').val());
            form.append("Ad", $('#name').val());
            form.append("Soyad", $('#surname').val());
            form.append("Konu", $('#subject').val());
            form.append("Mesaj", $('#message').val());
            form.append("Telefon", $('#phone').val());
            form.append("dosya", file[0]);
            if (file[0] === undefined || file[0] === null) {
                swal.fire({
                    text: "Please enter the CV information.",
                    icon: "error",
                    buttonsStyling: true,
                    confirmButtonText: "Ok",
                    customClass: {
                        confirmButton: "btn font-weight-bold btn-light-primary"
                    }
                })
            }
            else {
                $.ajax({
                url: '@Url.Action("EmailGonder", "Page")',
                type: "POST",
                processData: false,
                contentType: false,
                data: form,
                success: function (data) {
                    if (data.result == 1) {
                        swal.fire({
                            text: "Your message has been sent successfully.",
                            icon: "success",
                            buttonsStyling: true,
                            confirmButtonText: "Ok",
                            customClass: {
                                confirmButton: "btn font-weight-bold btn-light-primary"
                            }
                        })
                    }
                    else {
                        swal.fire({
                            text: "Message could not be sent.",
                            icon: "error",
                            buttonsStyling: true,
                            confirmButtonText: "Ok",
                            customClass: {
                                confirmButton: "btn font-weight-bold btn-light-primary"
                            }
                        })
                    }
                }
            });
            }


        }

        var habervalidator;

        function epostaGonder() {
            if (habervalidator.form()) {
                EpostaGonder();
                return false;
            }
            else {
                swal.fire({
                    text: "Please enter the information completely.",
                    icon: "error",
                    buttonsStyling: true,
                    confirmButtonText: "Ok",
                    customClass: {
                        confirmButton: "btn font-weight-bold btn-light-primary"
                    }
                })


                return false;
            }
        }
    </script>
}